eureka:
  client:
    registry-fetch-inteval-seconds: 5
    service-url:
      defaultZone: http://localhost:8700/eureka/

spring:
  data:
    cassandra:
      keyspace-name: royforthewin
      port: 9042
      contact-points: localhost
      username: cassandra
      password: cassandra


config:
  server:
    student-key: Hello There, from Config Server

